### ISSUE TITLE
Website throwing a TLS/privacy error

### ISSUE THREAD

**Issue by buildscientist** [emjun/tea-lang-web#1]
@emjun Hi there - I was going to post this issue in the tea-lang repo but thought it would be more appropriate to place here. 

Looks like Chrome/Firefox are complaining about TLS certificate errors. The cert itself is still valid but I believe it's for tea-lang.org not www.tea-lang.org

The link in the README in the tea-lang repo goes to www.tea-lang.org

If you update the CNAME record for www.tea-lang.org to go to tea-lang.org that should resolve the issue.

**Comment by emjun** [comment]
@buildscientist Thanks for pointing this out! 

@emeryberger Can you help with this?

**Comment by emeryberger** [comment]
For the interim, how about we just change the README to point to tea-lang.org?

**Comment by emjun** [comment]
@emeryberger The README is up to date.

**Comment by emjun** [comment]
We are going to stick to always using "tea-lang.org" whenever we point to the website. Thanks!
